imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines:     [ 'haml', 'twig' ]
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~

        # working configuration
        scssphp:
            import_paths:
                - %assets_dir%/bootstrap-sass-official/assets/stylesheets
            apply_to: "\.scss$"

        # probably working, need to fix GEM_PATH and load_paths
#        sass:
#            bin: /home/xstefanox/.gem/bin/sass
#            load_paths:
#                - %kernel.root_dir%/Resources/public/bootstrap-sass-official/assets/stylesheets
#            apply_to: "\.scss$"

        coffee:
            bin: %node_modules_bin%/coffee
            node: /usr/bin/node
            node_paths: [ %node_modules_bin% ]
            apply_to: "\.coffee$"
    assets:
        bower_css:
            inputs:
                - %assets_dir%/normalize.css/normalize.css
        bower_js:
            inputs:
                - %assets_dir%/jquery/dist/jquery.min.js
                - %assets_dir%/underscore/underscore.js
                - %assets_dir%/backbone/backbone.js

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

parameters:
    assets_dir:       %kernel.root_dir%/../bower_components
    node_modules_bin: %kernel.root_dir%/../node_modules/.bin
